export enum DOCTOR_PERMISSIONS {
  VIEW_APPOINTMENTS = "VIEW_APPOINTMENTS",
  MANAGE_APPOINTMENTS = "MANAGE_APPOINTMENTS",
  VIEW_PATIENTS = "VIEW_PATIENTS",
  WRITE_PRESCRIPTIONS = "WRITE_PRESCRIPTIONS",
  VIEW_REPORTS = "VIEW_REPORTS",
}
