export enum HOSPITAL_ADMIN_PERMISSIONS {
  MANAGE_DOCTORS = "MANAGE_DOCTORS",
  MANAGE_PATIENTS = "MANAGE_PATIENTS",
  MANAGE_APPOINTMENTS = "MANAGE_APPOINTMENTS",
  MANAGE_BILLING = "MANAGE_BILLING",
  VIEW_REPORTS = "VIEW_REPORTS",
}
